// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npm run bootstrap:admin",
  },
  engine: "classic",
  datasource: {
    // Runtime uses DATABASE_URL. When available, DIRECT_URL can be used by
    // Prisma CLI/migrations to connect straight to the database.
    url: process.env.DIRECT_URL?.trim() || env("DATABASE_URL"),
  },
});
